export const measurementMap = {
  neck: 'neck_circum_base',
  wrist: 'wrist_circum',
  sleeveLength: 'acromion_radial_stylion_len',
  underArm: 'scye_circum',
  chest: 'chest_circum',
  shortSleeve: 'acromion_radial_len',
  threeQuarterSleeve: 'arm_len_shoulder_elbow',
  shoulder: 'biacromial_breadth',
  roundElbow: 'elbow_circum',
  foreArm: 'forearm_circum',
  tommyCircumferenceTop: 'waist_circum_natural',
  ankle: 'ankle_circum',
  thighs: 'thigh_circum_proximal',
  crotchLength: 'u_crotch',
  roundKnee: 'knee_circum',
  trouserWaist: 'waist_circum_preferred',
  trouserInseam: 'jean_inseam',
  trouserHip: 'hip_circum',
  trouserLength: 'waist_height_preferred',
};

export const inverseMeasurementMap = {
  neck_circum_base: 'neck',
  wrist_circum: 'wrist',
  acromion_radial_stylion_len: 'sleeveLength',
  scye_circum: 'underArm',
  chest_circum: 'chest',
  acromion_radial_len: 'shortSleeve',
  arm_len_shoulder_elbow: 'threeQuarterSleeve',
  biacromial_breadth: 'shoulder',
  elbow_circum: 'roundElbow',
  forearm_circum: 'foreArm',
  waist_circum_natural: 'tommyCircumferenceTop',
  ankle_circum: 'ankle',
  thigh_circum_proximal: 'thighs',
  u_crotch: 'crotchLength',
  knee_circum: 'roundKnee',
  waist_circum_preferred: 'trouserWaist',
  jean_inseam: 'trouserInseam',
  hip_circum: 'trouserHip',
  waist_height_preferred: 'trouserLength',
};

export const friendlyNameMap = {
  neck_circum_base: 'neck',
  wrist_circum: 'wrist',
  acromion_radial_stylion_len: 'sleeve length',
  scye_circum: 'under arm',
  chest_circum: 'chest',
  acromion_radial_len: 'short sleeve',
  arm_len_shoulder_elbow: 'three quarter sleeve',
  biacromial_breadth: 'shoulder width',
  elbow_circum: 'round elbow',
  forearm_circum: 'forearm',
  waist_circum_natural: 'tummy circumference',
  ankle_circum: 'ankle',
  thigh_circum_proximal: 'thigh circumference',
  u_crotch: 'crotch length',
  knee_circum: 'round knee',
  waist_circum_preferred: 'trouser waist',
  jean_inseam: 'trouser inseam',
  hip_circum: 'trouser hip',
  waist_height_preferred: 'trouser length',
};
