export enum EventRole {
  bride = 'bride',
  groom = 'groom',
  BestMan = 'Best man',
  GroomsMan = 'Groomsman',
  MaidOfHonor = 'Maid of Honor',
  BridesMaid = 'Bridesmaid',
  ParentsOfBrideOrGroom = 'Parents (Bride or groom)',
  // ParentsOfGroom = 'parentsOfGroom',
  // Parents (Bride or groom)
  // Family member (Bride or groom)
  FamilyMemberOfBrideOrGroom = 'Family member (Bride or groom)',
  // FamilyMemberOfGroom = 'familyMemberOfGroom',
  FriendOfCouple = 'Friend of couple',
  EventPlanner = 'Event planner',
  Other = 'Other',
  Celebrant = 'Celebrant',
  PartnerOfCelebrant = 'Partner of celebrant',
  FriendOrFamilyOfCelebrant = 'Friend / family of celebrant',
  FriendOfCelebrant = 'Friend of celebrant',
  // FamilyOfCelebrant = 'familyOfCelebrant',
  // Friend / family of celebrant
  CsuiteExecutiveOfCompany = 'C-suite executive of Company',
  EmployeeOfCompany = 'Employee of company',
  Widow = 'Widow',
  Widower = 'Widower',
  FamilyMember = 'Family member',
  PlanningForMyself = 'Planning for myself',
  PlanningForSomeoneElse = 'Planning for someone else',
}
